sudo: required
notifications:
  email:
      - mrlee_23@naver.com
env:
  global:
      - GH_TOKEN=$G
      - PUBLISHED_DIR=".published"
services:
  - docker
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
