env:
    global:
        - ABCD="ABCDEFGH"
notifications:
    email:
        - mrlee_23@naver.com
language: node_js
node_js:
    - "8"
before_script:
    - bash ./build.sh
cache:
    directories:
        - "node_modules"
