notifications:
    email:
        - mrlee_23@naver.com
language: node_js
node_js:
    - "8"
#before_script:
#    - bash ./build.sh
ache:
    directories:
        - "node_modules"
deploy:
    provider: pages
    skip_celanup: true
    github_token: $G
    on:
        branch: master
