env:
    global:
        - GH_TOKEN=$G
notifications:
    email:
        - mrlee_23@naver.com
language: node_js
node_js:
    - "8"
before_script:
    - git config --global user.email "mrlee_23@naver.com"
    - git config --global user.name "mrlee23"
    - rm -rf ./.published
    - npm run doc
    - bash ./build.sh
    - git checkout master
cache:
    directories:
        - "node_modules"
